services:
  hw04.service-user:
    environment:
#      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_JPA_SHOW_SQL=true
      - JAVA_OPTS=-Ddebug=true
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT_ACTUATE=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD=DEBUG
#      - LOGGING_LEVEL_ORG_HIBERNATE=DEBUG
#      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK=DEBUG
#      - LOGGING_CLOUD_SLEUTH=DEBUG
