apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-service-ingress-rewrite
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/health/"
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /otusapp/vvsemenov/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: simple-service
                port:
                  number: 80